#DEEPSORT:
#  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
#  MAX_DIST: 0.2
#  MIN_CONFIDENCE: 0.3
#  NMS_MAX_OVERLAP: 0.5
#  MAX_IOU_DISTANCE: 0.7
#  MAX_AGE: 70
#  N_INIT: 3
#  NN_BUDGET: 100

#DEEPSORT:
#  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
#  MAX_DIST: 0.15
#  MIN_CONFIDENCE: 0.3
#  NMS_MAX_OVERLAP: 0.5
#  MAX_IOU_DISTANCE: 0.6
#  MAX_AGE: 70
#  N_INIT: 5
#  NN_BUDGET: 100

#DEEPSORT:
#  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
#  MAX_DIST: 0.25
#  MIN_CONFIDENCE: 0.25
#  NMS_MAX_OVERLAP: 0.5
#  MAX_IOU_DISTANCE: 0.5
#  MAX_AGE: 80
#  N_INIT: 6
#  NN_BUDGET: 300


#DEEPSORT:
#  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
#  MAX_DIST: 0.13
#  MIN_CONFIDENCE: 0.4
#  NMS_MAX_OVERLAP: 0.2
#  MAX_IOU_DISTANCE: 0.4
#  MAX_AGE: 300
#  N_INIT: 20
#  NN_BUDGET: 20

#DEEPSORT:
#  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
#  MAX_DIST: 0.3
#  MIN_CONFIDENCE: 0.4
#  NMS_MAX_OVERLAP: 0.4
#  MAX_IOU_DISTANCE: 0.7
#  MAX_AGE: 800
#  N_INIT: 20
#  NN_BUDGET: 20

#DEEPSORT:
#  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
#  REID_CLASSES_DIM: 751
#  MAX_DIST: 0.2
#  MIN_CONFIDENCE: 0.3
#  NMS_MAX_OVERLAP: 0.5
#  MAX_IOU_DISTANCE: 0.7
#  MAX_AGE: 70
#  N_INIT: 3
#  NN_BUDGET: 100

DEEPSORT:
  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.4  # Increase to allow for more appearance change tolerance
  MIN_CONFIDENCE: 0.3  # Decrease to allow more detections to be considered
  NMS_MAX_OVERLAP: 0.5  # Increase to allow more detections to be retained
  MAX_IOU_DISTANCE: 0.8  # Increase to allow more spatial overlap between detections
  MAX_AGE: 2000  # Increase to allow tracks to survive longer when occluded or not detected
  N_INIT: 15  # Decrease to make track initialization less conservative
  NN_BUDGET: 30  # Increase to improve the appearance model of each track
