#DEEPSORT:
#  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
#  MAX_DIST: 0.2
#  MIN_CONFIDENCE: 0.3
#  NMS_MAX_OVERLAP: 0.5
#  MAX_IOU_DISTANCE: 0.7
#  MAX_AGE: 70
#  N_INIT: 3
#  NN_BUDGET: 100

#DEEPSORT:
#  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
#  MAX_DIST: 0.15
#  MIN_CONFIDENCE: 0.3
#  NMS_MAX_OVERLAP: 0.5
#  MAX_IOU_DISTANCE: 0.6
#  MAX_AGE: 70
#  N_INIT: 5
#  NN_BUDGET: 100

#DEEPSORT:
#  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
#  MAX_DIST: 0.25
#  MIN_CONFIDENCE: 0.25
#  NMS_MAX_OVERLAP: 0.5
#  MAX_IOU_DISTANCE: 0.5
#  MAX_AGE: 80
#  N_INIT: 6
#  NN_BUDGET: 300


DEEPSORT:
  REID_CKPT: "/home/striker/Jetson/Xavier_NX/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.03
  MIN_CONFIDENCE: 0.8
  NMS_MAX_OVERLAP: 0.2
  MAX_IOU_DISTANCE: 0.4
  MAX_AGE: 200
  N_INIT: 20
  NN_BUDGET: 20
